ci: don't allow to merge if build fails

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -119,11 +119,25 @@ jobs:
         with:
           path: dist/${{ env.PROJECT_NAME }}/browser
 
+  ci:
+    name: CI
+    runs-on: ubuntu-latest
+    needs: [ quality, test, build ]
+    if: always()
+    steps:
+      - name: All CI checks passed
+        run: |
+          if [[ "${{ needs.quality.result }}" != "success" || "${{ needs.test.result }}" != "success" || "${{ needs.build.result }}" != "success" ]]; then
+            echo "One or more CI jobs failed."
+            exit 1
+          fi
+          echo "All CI checks passed."
+
   deploy:
     name: Deploy to GitHub Pages
     runs-on: ubuntu-latest
     timeout-minutes: 10
-    needs: build
+    needs: [ ci, build ]
     if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && github.event_name != 'pull_request'
     permissions:
       pages: write
